CREATE TABLE research_group (
    id UUID NOT NULL,
    address_city VARCHAR(120),
    address_complement VARCHAR(255),
    address_latitude DECIMAL(10, 7),
    address_longitude DECIMAL(10, 7),
    address_neighborhood VARCHAR(120),
    address_number VARCHAR(30),
    address_post_office_box VARCHAR(30),
    address_postal_code VARCHAR(8),
    address_state VARCHAR(2),
    address_street VARCHAR(255),
    cnpq_id VARCHAR(64) NOT NULL,
    contact_email VARCHAR(254),
    contact_fax VARCHAR(30),
    contact_phone VARCHAR(30),
    contact_website VARCHAR(2048),
    created_at DATETIME(6) NOT NULL,
    deleted_at DATETIME(6),
    formation_year INT NOT NULL,
    institution_name VARCHAR(255) NOT NULL,
    institution_unit VARCHAR(255),
    last_submitted_at DATETIME(6),
    name VARCHAR(255) NOT NULL,
    predominant_area VARCHAR(500) NOT NULL,
    repercussions TEXT,
    situation VARCHAR(50) NOT NULL,
    situation_at DATETIME(6),
    source_url VARCHAR(2048),
    updated_at DATETIME(6) NOT NULL,
    CONSTRAINT pk_research_group PRIMARY KEY (id),
    CONSTRAINT uk_research_group_cnpq_id UNIQUE (cnpq_id),
    INDEX idx_research_group_name (name)
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_uca1400_ai_ci;
